Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: public
  UploadServerUrl: http://127.0.0.1:8080/public
  UploadImageMaxSize: 10  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  UploadVideoMaxSize: 100  # MB
  UploadVideoAllowExts:
    - .mp4
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: simple_douyin
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: simple-douyin
  Issuer: zhouhao
  Expire: 7200
  IdentityKey: id